### ISSUE TITLE
compile.sh doesn't run on Windows

### ISSUE THREAD

**Issue by rwellborn** [facebookresearch/shaDow_GNN#1]
Is there an equivalent script that will do the same thing on Windows?

**Comment by ZimpleX** [comment]
Can you try running `.\install.bat` instead? I think I tried in windows terminal and it worked.

**Comment by rwellborn** [comment]
Thanks for the quick response, the issue is that I had to run through the troubleshooting section since pip couldn't install para_samplers initially. I believe I need to compile the .cpp file before I run `install.bat` but the compile.sh script doesn't run on Windows and unfortunately I am no good at working with C++ so I am not sure how to re-create it.

I did try running `install.bat` again after going through all of the other steps in the troubleshooting section but it still fails. Here is the output:

```
  Complete output (4 lines):
  running bdist_wheel
  running build
  running build_ext
  error: [WinError 2] The system cannot find the file specified
  ----------------------------------------
  ERROR: Failed building wheel for ParallelSampler
```

**Comment by ZimpleX** [comment]
You shouldn't need to compile `.cpp` in the process. In my case, I can run `.\install.bat` directly. 

However, I did notice some issues while trying to install it from scratch. Please double check if `shaDow/para_samplers/pybind11` directory is non-empty. Ideally, if you clone with `--recursive` flag, it shouldn't be empty, but I found that it appears to be empty for some unknown reason. 

If so, please execute the command `git submodule update --init --recursive`. Then please try `.\install.bat` again. 

Please let me know if the issue still persists.

**Comment by ZimpleX** [comment]
Thanks for the details. This sounds a bit strange to me -- on my machine, I can install `ParallelSampler` by executing the following commands in windows terminal:

```
conda create --name shadow python=3.8.5
conda activate shadow
conda install -c anaconda cmake
conda install -c conda-forge ninja
pip install pybind11
.\install.bat
```

For sanity check, could you please verify if you can do this [cmake example](https://github.com/pybind/cmake_example) provided by pybind11. 

Then, could you provide some more information about your environment. For example:

Did you use windows terminal?
What are your conda, python, cmake, ninja, pybind11 versions?

Also I noticed that the format of the error message seems a bit different from yours. When I encountered an error of the `install` script, I didn't find any keyword of "WinError" in my error messages. So maybe we are not using the same kind of terminal?

**Comment by rwellborn** [comment]
Whelp, looks like the problem was that I was trying to run `install.bat` outside of my environment. I just migrated away from using conda to pipenv and I needed to run `pipenv shell` before running the batch file. Thanks for the help troubleshooting this one, this is definitely user error.
