### ISSUE TITLE
Windows : Building wheel for ParallelSampler (setup.py) ... error

### ISSUE THREAD

**Issue by xiaomou-re** [facebookresearch/shaDow_GNN#3]
![Snipaste_2022-03-20_18-13-02](https://user-images.githubusercontent.com/66709858/159157719-67790456-4a33-4499-b166-442af333b8ed.png)

**Comment by ZimpleX** [comment]
Thanks for sharing! I just tested on my Windows laptop and couldn't reproduce your error. 

Here are some of my guesses:
* Have you installed Visual Studio C++? (you can install MS Visual Studio Community Edition, and select Visual C++)
* Maybe you can try adding cmake into PATH (see [this StackOverflow post](https://stackoverflow.com/questions/48624415/how-to-fix-cmake-error-in-cmakelists-txt-generator-nmake-makefiles-does-not-sup#52803626))?
* What is your cmake version? `cmake --version` for me outputs `3.18.2`

Please let me know if the error still persists.

**Comment by xiaomou-re** [comment]
The problem is solved after using Visual Studio C++. 
Thanks for your help!
