### ISSUE TITLE
Please share the requirement file.

### ISSUE THREAD

**Issue by intelsam** [facebookresearch/shaDow_GNN#5]
Hi, I have been trying to follow the installation guide mentioned. However, even after lot's of tries failed to do so.
Can you please share the requirement file?

For conda:
`conda list --explicit > req_conda.txt`

For pip:
`pip freeze > req_pip.txt`

Main culprit for me is the `torch-scatter` and `torch-sparse` libraries.

**Comment by ZimpleX** [comment]
Hi, thanks for you interest!

Please find below the requested files:

[req_conda.txt](https://github.com/facebookresearch/shaDow_GNN/files/10190945/req_conda.txt)

[req_pip.txt](https://github.com/facebookresearch/shaDow_GNN/files/10190946/req_pip.txt)


Please let me know if any issue still remains.

**Comment by intelsam** [comment]
Thanks a lot for sharing the files. Not sure what is the issue with my setup. 
I am getting this error:

`Traceback (most recent call last):
  File "/home/username/anaconda3/envs/sam_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/username/anaconda3/envs/sam_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/users/user/code/shaDow_GNN/shaDow/main.py", line 5, in <module>
    from graph_engine.frontend import TRAIN, VALID, TEST, MODE2STR, STR2MODE
  File "/home/username/.local/lib/python3.8/site-packages/graph_engine/frontend/__init__.py", line 2, in <module>
    from graph_engine.frontend import (
  File "/home/username/.local/lib/python3.8/site-packages/graph_engine/frontend/samplers_cpp.py", line 17, in <module>
    import ParallelSampler as cpp_para_sampler
ImportError: /home/username/.local/lib/python3.8/site-packages/ParallelSampler.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE`

The error is coming even though `ParallelSampler` was built successfully.

**Comment by intelsam** [comment]
@ZimpleX 
Maybe add the requirements file to the repo itself. I believe it'll be helpful for others too.

Also, I am closing the issue as you provided what I asked.

**Comment by ZimpleX** [comment]
Thanks for the suggestion. It makes good sense to me. I am working on cleaning up redundant logic in the code and preparing for the next release. Will include these requirement files in the next release.
